import { collection, addDoc, serverTimestamp, GeoPoint } from 'firebase/firestore';
import { db } from '../config/firebase';

// 15 realistic civic issues across Surat wards
const SEED_ISSUES = [
  {
    title: 'Large pothole near Adajan Patiya junction',
    description: 'Deep pothole approximately 40cm wide on main road, causing vehicles to swerve dangerously.',
    category: 'pothole', severity: 4, status: 'verified',
    location: { lat: 21.2093, lng: 72.7947 },
    address: 'Adajan Patiya, Adajan, Surat, Gujarat 395009',
    wardName: 'Adajan', votes: 5,
    voterIds: ['seed1', 'seed2', 'seed3', 'seed4', 'seed5'],
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Pothole_on_road.jpg/640px-Pothole_on_road.jpg',
    aiAnalysis: { category: 'pothole', severity: 4, confidence: 0.94, description: 'Large pothole on road surface', tags: ['road damage', 'pothole', 'hazard'] },
    priorityScore: 20,
  },
  {
    title: 'Water pipe burst on Vesu main road',
    description: 'Underground water pipe leaking — water flooding footpath since 2 days.',
    category: 'water_leak', severity: 5, status: 'reported',
    location: { lat: 21.1488, lng: 72.7799 },
    address: 'Vesu Canal Road, Vesu, Surat, Gujarat 395007',
    wardName: 'Vesu', votes: 2,
    voterIds: ['seed1', 'seed6'],
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Water_main_break.jpg/640px-Water_main_break.jpg',
    aiAnalysis: { category: 'water_leak', severity: 5, confidence: 0.88, description: 'Major water pipe burst flooding street', tags: ['water leak', 'burst pipe', 'flooding'] },
    priorityScore: 10,
  },
  {
    title: 'Street light not working — Katargam area',
    description: 'Three consecutive street lights have been non-functional for a week. Dark area unsafe at night.',
    category: 'streetlight', severity: 3, status: 'verified',
    location: { lat: 21.2270, lng: 72.8418 },
    address: 'Katargam Road, Katargam, Surat, Gujarat 395004',
    wardName: 'Katargam', votes: 4,
    voterIds: ['seed1', 'seed2', 'seed3', 'seed4'],
    photoUrl: '',
    aiAnalysis: { category: 'streetlight', severity: 3, confidence: 0.82, description: 'Multiple street lights non-functional creating safety risk', tags: ['street light', 'dark area', 'safety'] },
    priorityScore: 12,
  },
  {
    title: 'Garbage overflow near Athwa residential area',
    description: 'Municipal garbage bin overflowing for 3 days. Waste spread on road attracting stray animals.',
    category: 'waste', severity: 3, status: 'reported',
    location: { lat: 21.1788, lng: 72.8306 },
    address: 'Athwa Lines, Athwa, Surat, Gujarat 395001',
    wardName: 'Athwa', votes: 1,
    voterIds: ['seed2'],
    photoUrl: '',
    aiAnalysis: { category: 'waste', severity: 3, confidence: 0.91, description: 'Overflowing garbage bin creating health hazard', tags: ['garbage', 'waste', 'health hazard'] },
    priorityScore: 3,
  },
  {
    title: 'Pothole cluster on Piplod internal road',
    description: 'Series of 5 potholes on residential road. Several two-wheelers have fallen.',
    category: 'pothole', severity: 4, status: 'in_progress',
    location: { lat: 21.1633, lng: 72.7880 },
    address: 'Piplod Society Road, Piplod, Surat, Gujarat 395007',
    wardName: 'Piplod', votes: 8,
    voterIds: ['seed1','seed2','seed3','seed4','seed5','seed6','seed7','seed8'],
    photoUrl: '',
    aiAnalysis: { category: 'pothole', severity: 4, confidence: 0.96, description: 'Multiple potholes on residential road causing accidents', tags: ['pothole', 'road damage', 'accident risk'] },
    priorityScore: 32,
  },
  {
    title: 'Open manhole on Althan road',
    description: 'Manhole cover missing. Extremely dangerous for pedestrians and cyclists, especially at night.',
    category: 'other', severity: 5, status: 'verified',
    location: { lat: 21.1418, lng: 72.8071 },
    address: 'Althan Tenament Road, Althan, Surat, Gujarat 395017',
    wardName: 'Althan', votes: 6,
    voterIds: ['seed1','seed2','seed3','seed4','seed5','seed6'],
    photoUrl: '',
    aiAnalysis: { category: 'other', severity: 5, confidence: 0.97, description: 'Open uncovered manhole posing critical safety risk', tags: ['manhole', 'safety hazard', 'critical'] },
    priorityScore: 30,
  },
  {
    title: 'Waterlogging after rain in Rander',
    description: 'Blocked storm drain causing water to accumulate up to 1 foot on main road.',
    category: 'water_leak', severity: 3, status: 'reported',
    location: { lat: 21.2302, lng: 72.7755 },
    address: 'Rander Road, Rander, Surat, Gujarat 395005',
    wardName: 'Rander', votes: 0, voterIds: [],
    photoUrl: '',
    aiAnalysis: { category: 'water_leak', severity: 3, confidence: 0.78, description: 'Blocked drain causing road waterlogging', tags: ['waterlogging', 'drain', 'flooding'] },
    priorityScore: 3,
  },
  {
    title: 'Damaged footpath in Varachha',
    description: 'Footpath tiles broken and uplifted creating trip hazard for elderly and children.',
    category: 'other', severity: 2, status: 'reported',
    location: { lat: 21.2100, lng: 72.8600 },
    address: 'Varachha Road, Varachha, Surat, Gujarat 395006',
    wardName: 'Varachha', votes: 1, voterIds: ['seed3'],
    photoUrl: '',
    aiAnalysis: { category: 'other', severity: 2, confidence: 0.85, description: 'Broken footpath tiles causing trip hazard', tags: ['footpath', 'broken tiles', 'trip hazard'] },
    priorityScore: 2,
  },
  {
    title: 'Broken street light Udhna junction',
    description: 'Major junction has no street lighting making it dangerous for night traffic.',
    category: 'streetlight', severity: 4, status: 'verified',
    location: { lat: 21.1808, lng: 72.8517 },
    address: 'Udhna Darwaja, Udhna, Surat, Gujarat 394210',
    wardName: 'Udhna', votes: 5,
    voterIds: ['seed1','seed2','seed3','seed4','seed5'],
    photoUrl: '',
    aiAnalysis: { category: 'streetlight', severity: 4, confidence: 0.9, description: 'Non-functional street lights at busy junction', tags: ['street light', 'junction', 'traffic safety'] },
    priorityScore: 20,
  },
  {
    title: 'Garbage burning near City Light',
    description: 'Residents burning garbage illegally causing air pollution and fire risk.',
    category: 'waste', severity: 4, status: 'reported',
    location: { lat: 21.1553, lng: 72.7764 },
    address: 'City Light Road, City Light, Surat, Gujarat 395007',
    wardName: 'City Light', votes: 2, voterIds: ['seed4', 'seed5'],
    photoUrl: '',
    aiAnalysis: { category: 'waste', severity: 4, confidence: 0.87, description: 'Illegal garbage burning causing air pollution and fire hazard', tags: ['garbage burning', 'pollution', 'fire risk'] },
    priorityScore: 8,
  },
  {
    title: 'Water leakage from overhead tank',
    description: 'Municipal overhead water tank leaking continuously. Water wastage for 5 days.',
    category: 'water_leak', severity: 3, status: 'resolved',
    location: { lat: 21.1750, lng: 72.8200 },
    address: 'Sarthana Jakatnaka, Sarthana, Surat, Gujarat 395006',
    wardName: 'Sarthana', votes: 7,
    voterIds: ['seed1','seed2','seed3','seed4','seed5','seed6','seed7'],
    photoUrl: '',
    aiAnalysis: { category: 'water_leak', severity: 3, confidence: 0.92, description: 'Overhead tank leaking causing water wastage', tags: ['water tank', 'leak', 'water wastage'] },
    priorityScore: 21,
  },
  {
    title: 'Deep pothole near Majura Gate flyover',
    description: 'Pothole has formed at the base of the flyover. Several vehicles have been damaged.',
    category: 'pothole', severity: 4, status: 'verified',
    location: { lat: 21.1935, lng: 72.8300 },
    address: 'Majura Gate, Ring Road, Surat, Gujarat 395002',
    wardName: 'Ring Road', votes: 4,
    voterIds: ['seed1','seed2','seed3','seed4'],
    photoUrl: '',
    aiAnalysis: { category: 'pothole', severity: 4, confidence: 0.93, description: 'Significant road pothole near flyover causing vehicle damage', tags: ['pothole', 'flyover', 'road damage'] },
    priorityScore: 16,
  },
  {
    title: 'Sewage overflow in Nanpura',
    description: 'Blocked sewer line causing sewage to overflow onto footpath and road.',
    category: 'water_leak', severity: 5, status: 'reported',
    location: { lat: 21.1942, lng: 72.8385 },
    address: 'Nanpura, Surat, Gujarat 395001',
    wardName: 'Nanpura', votes: 3,
    voterIds: ['seed5','seed6','seed7'],
    photoUrl: '',
    aiAnalysis: { category: 'water_leak', severity: 5, confidence: 0.95, description: 'Sewage overflow creating serious health hazard', tags: ['sewage', 'overflow', 'health hazard'] },
    priorityScore: 15,
  },
  {
    title: 'Broken road divider on Dumas Road',
    description: 'Road divider damaged and lying on road. Creates traffic hazard especially at night.',
    category: 'other', severity: 3, status: 'reported',
    location: { lat: 21.1370, lng: 72.7720 },
    address: 'Dumas Road, Dumas, Surat, Gujarat 395006',
    wardName: 'Dumas', votes: 0, voterIds: [],
    photoUrl: '',
    aiAnalysis: { category: 'other', severity: 3, confidence: 0.88, description: 'Damaged road divider creating traffic hazard', tags: ['road divider', 'traffic', 'hazard'] },
    priorityScore: 3,
  },
  {
    title: 'Street lights damaged after storm in Bhatar',
    description: 'Heavy rain caused two electricity poles to tilt. Street lights hanging dangerously.',
    category: 'streetlight', severity: 5, status: 'in_progress',
    location: { lat: 21.1705, lng: 72.8170 },
    address: 'Bhatar Road, Bhatar, Surat, Gujarat 395017',
    wardName: 'Bhatar', votes: 9,
    voterIds: ['seed1','seed2','seed3','seed4','seed5','seed6','seed7','seed8','seed9'],
    photoUrl: '',
    aiAnalysis: { category: 'streetlight', severity: 5, confidence: 0.98, description: 'Storm-damaged electricity poles with hanging lights creating electrocution risk', tags: ['electricity pole', 'storm damage', 'electrocution risk'] },
    priorityScore: 45,
  },
];

export async function seedDatabase() {
  console.log('Starting seed...');
  const issuesRef = collection(db, 'issues');

  for (const issue of SEED_ISSUES) {
    const { location, ...rest } = issue;
    try {
      await addDoc(issuesRef, {
        ...rest,
        location: new GeoPoint(location.lat, location.lng),
        reportedBy: 'seed_user',
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });
      console.log(`✅ Added: ${issue.title}`);
    } catch (e) {
      console.error(`❌ Failed: ${issue.title}`, e);
    }
  }

  console.log('Seed complete.');
}